# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.helloUser_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.helloUser_label.setFont(font)
        self.helloUser_label.setObjectName("helloUser_label")
        self.verticalLayout.addWidget(self.helloUser_label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.my_account_tab = QtWidgets.QWidget()
        self.my_account_tab.setObjectName("my_account_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.my_account_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.myStocks_groupBox = QtWidgets.QGroupBox(self.my_account_tab)
        self.myStocks_groupBox.setObjectName("myStocks_groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.myStocks_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.myStocks_tableWidget = QtWidgets.QTableWidget(self.myStocks_groupBox)
        self.myStocks_tableWidget.setAcceptDrops(False)
        self.myStocks_tableWidget.setAutoFillBackground(False)
        self.myStocks_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.myStocks_tableWidget.setAlternatingRowColors(True)
        self.myStocks_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.myStocks_tableWidget.setObjectName("myStocks_tableWidget")
        self.myStocks_tableWidget.setColumnCount(5)
        self.myStocks_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.myStocks_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.myStocks_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.myStocks_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.myStocks_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.myStocks_tableWidget.setHorizontalHeaderItem(4, item)
        self.myStocks_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.myStocks_tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.myStocks_tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addStocks_comboBox = QtWidgets.QComboBox(self.myStocks_groupBox)
        self.addStocks_comboBox.setObjectName("addStocks_comboBox")
        self.horizontalLayout_4.addWidget(self.addStocks_comboBox)
        self.addStocks_pushButton = QtWidgets.QPushButton(self.myStocks_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStocks_pushButton.sizePolicy().hasHeightForWidth())
        self.addStocks_pushButton.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.addStocks_pushButton.setPalette(palette)
        self.addStocks_pushButton.setAcceptDrops(True)
        self.addStocks_pushButton.setObjectName("addStocks_pushButton")
        self.horizontalLayout_4.addWidget(self.addStocks_pushButton)
        self.deleteStocks_pushButton = QtWidgets.QPushButton(self.myStocks_groupBox)
        self.deleteStocks_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteStocks_pushButton.sizePolicy().hasHeightForWidth())
        self.deleteStocks_pushButton.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.deleteStocks_pushButton.setPalette(palette)
        self.deleteStocks_pushButton.setObjectName("deleteStocks_pushButton")
        self.horizontalLayout_4.addWidget(self.deleteStocks_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addWidget(self.myStocks_groupBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.myMessages_groupBox = QtWidgets.QGroupBox(self.my_account_tab)
        self.myMessages_groupBox.setObjectName("myMessages_groupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.myMessages_groupBox)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.myMessages_tableWidget = QtWidgets.QTableWidget(self.myMessages_groupBox)
        self.myMessages_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.myMessages_tableWidget.setAlternatingRowColors(True)
        self.myMessages_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.myMessages_tableWidget.setObjectName("myMessages_tableWidget")
        self.myMessages_tableWidget.setColumnCount(4)
        self.myMessages_tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myMessages_tableWidget.setItem(2, 3, item)
        self.myMessages_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_17.addWidget(self.myMessages_tableWidget)
        self.verticalLayout_8.addWidget(self.myMessages_groupBox)
        self.tabWidget.addTab(self.my_account_tab, "")
        self.all_stocks_tab = QtWidgets.QWidget()
        self.all_stocks_tab.setObjectName("all_stocks_tab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.all_stocks_tab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.allStocks_groupBox = QtWidgets.QGroupBox(self.all_stocks_tab)
        self.allStocks_groupBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.allStocks_groupBox.setObjectName("allStocks_groupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.allStocks_groupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.allStocks_tableWidget = QtWidgets.QTableWidget(self.allStocks_groupBox)
        self.allStocks_tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.allStocks_tableWidget.setAcceptDrops(False)
        self.allStocks_tableWidget.setAutoFillBackground(False)
        self.allStocks_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.allStocks_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.allStocks_tableWidget.setTabKeyNavigation(True)
        self.allStocks_tableWidget.setProperty("showDropIndicator", True)
        self.allStocks_tableWidget.setAlternatingRowColors(True)
        self.allStocks_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.allStocks_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.allStocks_tableWidget.setWordWrap(True)
        self.allStocks_tableWidget.setCornerButtonEnabled(True)
        self.allStocks_tableWidget.setObjectName("allStocks_tableWidget")
        self.allStocks_tableWidget.setColumnCount(5)
        self.allStocks_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.allStocks_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.allStocks_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.allStocks_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.allStocks_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.allStocks_tableWidget.setHorizontalHeaderItem(4, item)
        self.allStocks_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.allStocks_tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_14.addWidget(self.allStocks_tableWidget)
        self.verticalLayout_15.addWidget(self.allStocks_groupBox)
        self.stockInfo_groupBox = QtWidgets.QGroupBox(self.all_stocks_tab)
        self.stockInfo_groupBox.setObjectName("stockInfo_groupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.stockInfo_groupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.stockInfo_tabWidget = QtWidgets.QTabWidget(self.stockInfo_groupBox)
        self.stockInfo_tabWidget.setObjectName("stockInfo_tabWidget")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.stockInfo_tabWidget.addTab(self.info, "")
        self.tweets = QtWidgets.QWidget()
        self.tweets.setObjectName("tweets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tweets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tweets_tableWidget = QtWidgets.QTableWidget(self.tweets)
        self.tweets_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tweets_tableWidget.setAlternatingRowColors(True)
        self.tweets_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tweets_tableWidget.setObjectName("tweets_tableWidget")
        self.tweets_tableWidget.setColumnCount(4)
        self.tweets_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tweets_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tweets_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tweets_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tweets_tableWidget.setHorizontalHeaderItem(3, item)
        self.tweets_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tweets_tableWidget)
        self.stockInfo_tabWidget.addTab(self.tweets, "")
        self.regression = QtWidgets.QWidget()
        self.regression.setObjectName("regression")
        self.stockInfo_tabWidget.addTab(self.regression, "")
        self.verticalLayout_16.addWidget(self.stockInfo_tabWidget)
        self.verticalLayout_15.addWidget(self.stockInfo_groupBox)
        self.tabWidget.addTab(self.all_stocks_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stockInfo_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.helloUser_label.setText(_translate("MainWindow", "Hello User"))
        self.myStocks_groupBox.setTitle(_translate("MainWindow", "My stocks"))
        self.myStocks_tableWidget.setSortingEnabled(True)
        item = self.myStocks_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.myStocks_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.myStocks_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Country"))
        item = self.myStocks_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Industry"))
        item = self.myStocks_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sub Sector"))
        self.addStocks_pushButton.setText(_translate("MainWindow", "Add Stocks"))
        self.deleteStocks_pushButton.setText(_translate("MainWindow", "Delete Stock"))
        self.myMessages_groupBox.setTitle(_translate("MainWindow", "My messages"))
        self.myMessages_tableWidget.setSortingEnabled(True)
        item = self.myMessages_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.myMessages_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.myMessages_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.myMessages_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.myMessages_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.myMessages_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prediction"))
        item = self.myMessages_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "True Prediction"))
        __sortingEnabled = self.myMessages_tableWidget.isSortingEnabled()
        self.myMessages_tableWidget.setSortingEnabled(False)
        item = self.myMessages_tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "01/01/2018"))
        item = self.myMessages_tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "GOOG"))
        item = self.myMessages_tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Rise"))
        item = self.myMessages_tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "N/A"))
        item = self.myMessages_tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "01/01/2018"))
        item = self.myMessages_tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "FB"))
        item = self.myMessages_tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Fall"))
        item = self.myMessages_tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "N/A"))
        item = self.myMessages_tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "01/01/2018"))
        item = self.myMessages_tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "AAPL"))
        item = self.myMessages_tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "Same"))
        item = self.myMessages_tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "N/A"))
        self.myMessages_tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.my_account_tab), _translate("MainWindow", "My Account"))
        self.allStocks_groupBox.setTitle(_translate("MainWindow", "All stocks"))
        self.allStocks_tableWidget.setSortingEnabled(True)
        item = self.allStocks_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.allStocks_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.allStocks_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Country"))
        item = self.allStocks_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Industry"))
        item = self.allStocks_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sub Sector"))
        self.stockInfo_groupBox.setTitle(_translate("MainWindow", "Stock Information"))
        self.label.setText(_translate("MainWindow", "Explanation:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.stockInfo_tabWidget.setTabText(self.stockInfo_tabWidget.indexOf(self.info), _translate("MainWindow", "Info"))
        self.tweets_tableWidget.setSortingEnabled(True)
        item = self.tweets_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tweets_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Followers"))
        item = self.tweets_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sentiment"))
        item = self.tweets_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "text"))
        self.stockInfo_tabWidget.setTabText(self.stockInfo_tabWidget.indexOf(self.tweets), _translate("MainWindow", "Tweets"))
        self.stockInfo_tabWidget.setTabText(self.stockInfo_tabWidget.indexOf(self.regression), _translate("MainWindow", "Regression"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.all_stocks_tab), _translate("MainWindow", "All Stocks"))

