# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUpIn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.sign_up_page = QtWidgets.QWidget()
        self.sign_up_page.setGeometry(QtCore.QRect(0, 0, 581, 331))
        self.sign_up_page.setObjectName("sign_up_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sign_up_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.firstName_label = QtWidgets.QLabel(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.firstName_label.setFont(font)
        self.firstName_label.setObjectName("firstName_label")
        self.verticalLayout_3.addWidget(self.firstName_label)
        self.lastName_label = QtWidgets.QLabel(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lastName_label.setFont(font)
        self.lastName_label.setObjectName("lastName_label")
        self.verticalLayout_3.addWidget(self.lastName_label)
        self.email_label = QtWidgets.QLabel(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.verticalLayout_3.addWidget(self.email_label)
        self.phoneNumber_label = QtWidgets.QLabel(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.phoneNumber_label.setFont(font)
        self.phoneNumber_label.setObjectName("phoneNumber_label")
        self.verticalLayout_3.addWidget(self.phoneNumber_label)
        self.password_label = QtWidgets.QLabel(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout_3.addWidget(self.password_label)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.firstName_lineEdit = QtWidgets.QLineEdit(self.sign_up_page)
        self.firstName_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.firstName_lineEdit.setClearButtonEnabled(False)
        self.firstName_lineEdit.setObjectName("firstName_lineEdit")
        self.verticalLayout_4.addWidget(self.firstName_lineEdit)
        self.lastName_lineEdit = QtWidgets.QLineEdit(self.sign_up_page)
        self.lastName_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lastName_lineEdit.setClearButtonEnabled(False)
        self.lastName_lineEdit.setObjectName("lastName_lineEdit")
        self.verticalLayout_4.addWidget(self.lastName_lineEdit)
        self.email_lineEdit = QtWidgets.QLineEdit(self.sign_up_page)
        self.email_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.email_lineEdit.setClearButtonEnabled(False)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout_4.addWidget(self.email_lineEdit)
        self.phoneNumber_lineEdit = QtWidgets.QLineEdit(self.sign_up_page)
        self.phoneNumber_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.phoneNumber_lineEdit.setClearButtonEnabled(False)
        self.phoneNumber_lineEdit.setObjectName("phoneNumber_lineEdit")
        self.verticalLayout_4.addWidget(self.phoneNumber_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.sign_up_page)
        self.password_lineEdit.setEnabled(True)
        self.password_lineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.password_lineEdit.setClearButtonEnabled(False)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_4.addWidget(self.password_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.error_label = QtWidgets.QLabel(self.sign_up_page)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout_10.addWidget(self.error_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.sign_up_page)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_10.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_10)
        self.toolBox.addItem(self.sign_up_page, "")
        self.sign_in_page = QtWidgets.QWidget()
        self.sign_in_page.setGeometry(QtCore.QRect(0, 0, 581, 331))
        self.sign_in_page.setObjectName("sign_in_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sign_in_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.email_label_2 = QtWidgets.QLabel(self.sign_in_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.email_label_2.setFont(font)
        self.email_label_2.setObjectName("email_label_2")
        self.verticalLayout_12.addWidget(self.email_label_2)
        self.password_label_2 = QtWidgets.QLabel(self.sign_in_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.password_label_2.setFont(font)
        self.password_label_2.setObjectName("password_label_2")
        self.verticalLayout_12.addWidget(self.password_label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.email_lineEdit_2 = QtWidgets.QLineEdit(self.sign_in_page)
        self.email_lineEdit_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.email_lineEdit_2.setObjectName("email_lineEdit_2")
        self.verticalLayout_13.addWidget(self.email_lineEdit_2)
        self.password_lineEdit_2 = QtWidgets.QLineEdit(self.sign_in_page)
        self.password_lineEdit_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.password_lineEdit_2.setObjectName("password_lineEdit_2")
        self.verticalLayout_13.addWidget(self.password_lineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.error_label_2 = QtWidgets.QLabel(self.sign_in_page)
        self.error_label_2.setText("")
        self.error_label_2.setObjectName("error_label_2")
        self.verticalLayout_11.addWidget(self.error_label_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.sign_in_page)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.buttonBox_2.setFont(font)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.verticalLayout_11.addWidget(self.buttonBox_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.toolBox.addItem(self.sign_in_page, "")
        self.verticalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.firstName_label.setText(_translate("MainWindow", "First name:"))
        self.lastName_label.setText(_translate("MainWindow", "Last name:"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.phoneNumber_label.setText(_translate("MainWindow", "Phone number:"))
        self.password_label.setText(_translate("MainWindow", "Password:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sign_up_page), _translate("MainWindow", "Sign Up"))
        self.email_label_2.setText(_translate("MainWindow", "Email:"))
        self.password_label_2.setText(_translate("MainWindow", "Password:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sign_in_page), _translate("MainWindow", "Sign In"))

