# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUpIn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(565, 448)
        Form.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.signup_tab = QtWidgets.QWidget()
        self.signup_tab.setObjectName("signup_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.signup_tab)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.firstName_label = QtWidgets.QLabel(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.firstName_label.setFont(font)
        self.firstName_label.setObjectName("firstName_label")
        self.verticalLayout_2.addWidget(self.firstName_label)
        self.lastName_label = QtWidgets.QLabel(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lastName_label.setFont(font)
        self.lastName_label.setObjectName("lastName_label")
        self.verticalLayout_2.addWidget(self.lastName_label)
        self.email_label = QtWidgets.QLabel(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.verticalLayout_2.addWidget(self.email_label)
        self.phoneNumber_label = QtWidgets.QLabel(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.phoneNumber_label.setFont(font)
        self.phoneNumber_label.setObjectName("phoneNumber_label")
        self.verticalLayout_2.addWidget(self.phoneNumber_label)
        self.password_label = QtWidgets.QLabel(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout_2.addWidget(self.password_label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.firstName_lineEdit = QtWidgets.QLineEdit(self.signup_tab)
        self.firstName_lineEdit.setClearButtonEnabled(False)
        self.firstName_lineEdit.setObjectName("firstName_lineEdit")
        self.verticalLayout_3.addWidget(self.firstName_lineEdit)
        self.lastName_lineEdit = QtWidgets.QLineEdit(self.signup_tab)
        self.lastName_lineEdit.setClearButtonEnabled(False)
        self.lastName_lineEdit.setObjectName("lastName_lineEdit")
        self.verticalLayout_3.addWidget(self.lastName_lineEdit)
        self.email_lineEdit = QtWidgets.QLineEdit(self.signup_tab)
        self.email_lineEdit.setClearButtonEnabled(False)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout_3.addWidget(self.email_lineEdit)
        self.phoneNumber_lineEdit = QtWidgets.QLineEdit(self.signup_tab)
        self.phoneNumber_lineEdit.setClearButtonEnabled(False)
        self.phoneNumber_lineEdit.setObjectName("phoneNumber_lineEdit")
        self.verticalLayout_3.addWidget(self.phoneNumber_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.signup_tab)
        self.password_lineEdit.setEnabled(True)
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.password_lineEdit.setClearButtonEnabled(False)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_3.addWidget(self.password_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.error_label = QtWidgets.QLabel(self.signup_tab)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout_10.addWidget(self.error_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.signup_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        
        self.buttonBox.clicked.connect(signIn)
        
        self.verticalLayout_10.addWidget(self.buttonBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.signup_tab, "")
        self.signin_tab = QtWidgets.QWidget()
        self.signin_tab.setObjectName("signin_tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.signin_tab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.email_label_2 = QtWidgets.QLabel(self.signin_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.email_label_2.setFont(font)
        self.email_label_2.setObjectName("email_label_2")
        self.verticalLayout_12.addWidget(self.email_label_2)
        self.password_label_2 = QtWidgets.QLabel(self.signin_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.password_label_2.setFont(font)
        self.password_label_2.setObjectName("password_label_2")
        self.verticalLayout_12.addWidget(self.password_label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.email_lineEdit_2 = QtWidgets.QLineEdit(self.signin_tab)
        self.email_lineEdit_2.setObjectName("email_lineEdit_2")
        self.verticalLayout_13.addWidget(self.email_lineEdit_2)
        self.password_lineEdit_2 = QtWidgets.QLineEdit(self.signin_tab)
        self.password_lineEdit_2.setObjectName("password_lineEdit_2")
        self.verticalLayout_13.addWidget(self.password_lineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.error_label_2 = QtWidgets.QLabel(self.signin_tab)
        self.error_label_2.setText("")
        self.error_label_2.setObjectName("error_label_2")
        self.verticalLayout_11.addWidget(self.error_label_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.signin_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.buttonBox_2.setFont(font)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.verticalLayout_11.addWidget(self.buttonBox_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.signin_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sign Up/In"))
        self.firstName_label.setText(_translate("Form", "First name:"))
        self.lastName_label.setText(_translate("Form", "Last name:"))
        self.email_label.setText(_translate("Form", "Email:"))
        self.phoneNumber_label.setText(_translate("Form", "Phone number:"))
        self.password_label.setText(_translate("Form", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signup_tab), _translate("Form", "SignUp"))
        self.email_label_2.setText(_translate("Form", "Email:"))
        self.password_label_2.setText(_translate("Form", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signin_tab), _translate("Form", "Signin"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


def signIn():
    #move to main ui
    print("gallll")